from client.scrapers.whoscored.player.passing import crawl_player_passing_stats
from client.scrapers.whoscored.player.overall import crawl_player_overall_stats
from client.scrapers.whoscored.player.defensive import crawl_player_defensive_stats
from client.scrapers.whoscored.player.offensive import crawl_player_offensive_stats
